from typing import Union

ObjType = Union[int, float, str, bool, bytes, list, tuple, dict, None]
ByteLike = Union[bytes, bytearray]
NUMBER_BASE = 255
ENDING_FLAG = 255
HEADER = b"<o>"
BIG_ENDIAN_DOUBLE_FORMAT = "!d"
BYTES_IN_DOUBLE = 8
NUMBER_OF_BITS_IN_BYTE = 8
LEFTMOST_BIT_MASK = 128
NEGATIVE_NUMBER_SIGN = NUMBER_BASE - 1
INVALID_UTF_8_START_BYTE_COMPACT_ASCII = 0xfe

EMPTY_STR_FLAG = 0
EMPTY_BYTES_FLAG = 1
TRUE_FLAG = 2
FALSE_FLAG = 3
NULL_FLAG = 4
FIRST_FLAGS_LIST = ["", b"", True, False, None]
EMPTY_LIST_FLAG = 5
EMPTY_DICT_FLAG = 6
POSITIVE_INT_FLAG = 7
NEGATIVE_INT_FLAG = 8
FLOAT_FLAG = 9
STR_FLAG = 10
BYTES_FLAG = 11
BOOL_FLAG = 12
LIST_FLAG = 13
CONSISTENT_TYPE_LIST_FLAG = 14
DICT_FLAG = 15
STR_KEY_DICT_FLAG = 16
POINTER_FLAG = 17
ASCII_STR_FLAG = 18
LIST_OF_STRUCTURED_DICTS_FLAG = 19
POINTER_FLAG_1BYTE = 20
POINTER_FLAG_2BYTE = 21
POINTER_FLAG_3BYTE = 22
POINTER_FLAG_4BYTE = 23

AMOUNT_OF_USED_FLAGS = 30   # for future flags
