name: Upload Python Package

on:
  release:
    types: [published] # This is now the ONLY trigger


permissions:
  contents: read

jobs:
  run-tests:
    uses: ./.github/workflows/test.yml

  release-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    needs: run-tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build Wheels
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release --out dist --find-interpreter
          manylinux: ${{ matrix.os == 'ubuntu-latest' && 'auto' || '' }}

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists-${{ matrix.os }}
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/p/pypinch

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
